[tool.poetry]
name = "honulabs"
version = "0.1.0"
description = "Honulabs CLI"
authors = ["freyamade <freya.broderick@honu.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
